spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml #XML ?? ?? ?? ??
  type-aliases-package: com.back.domain.**.dto # resultType ??? ??
logging:
  level:
    com.back: debug